// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyCuaHangTapHoa.Infrastructure;

#nullable disable

namespace QuanLyCuaHangTapHoa.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615151041_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyCuaHangTapHoa.Domain.ChiTietDonHang", b =>
                {
                    b.Property<string>("MaDon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaSP")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaDon", "MaSP");

                    b.HasIndex("MaSP");

                    b.ToTable("ChiTietDonHangs", (string)null);
                });

            modelBuilder.Entity("QuanLyCuaHangTapHoa.Domain.DonDatHang", b =>
                {
                    b.Property<string>("MaDon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaNguoiDungKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayDuyet")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThaiDonHang")
                        .HasColumnType("int");

                    b.HasKey("MaDon");

                    b.HasIndex("MaNguoiDungKhachHang");

                    b.ToTable("DonDatHangs", (string)null);
                });

            modelBuilder.Entity("QuanLyCuaHangTapHoa.Domain.HoaDon", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaDon")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaNguoiDungNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaDon");

                    b.HasIndex("MaNguoiDungNhanVien");

                    b.ToTable("HoaDons", (string)null);
                });

            modelBuilder.Entity("QuanLyCuaHangTapHoa.Domain.NguoiDung", b =>
                {
                    b.Property<string>("MaNguoiDung")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SoDienThoai")
                        .IsUnique();

                    b.ToTable("NguoiDungs", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("QuanLyCuaHangTapHoa.Domain.SanPham", b =>
                {
                    b.Property<string>("MaSP")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DanhMuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TrangThaiSanPham")
                        .HasColumnType("int");

                    b.HasKey("MaSP");

                    b.ToTable("SanPhams", (string)null);

                    b.HasData(
                        new
                        {
                            MaSP = "SP001",
                            DanhMuc = "Do uong",
                            DonGia = 35000m,
                            SoLuongTon = 50,
                            TenSP = "Sua tuoi Vinamilk 1L",
                            TrangThaiSanPham = 0
                        },
                        new
                        {
                            MaSP = "SP002",
                            DanhMuc = "Banh keo",
                            DonGia = 18000m,
                            SoLuongTon = 100,
                            TenSP = "Banh qui Oreo 133g",
                            TrangThaiSanPham = 0
                        },
                        new
                        {
                            MaSP = "SP003",
                            DanhMuc = "Thuc pham an lien",
                            DonGia = 4500m,
                            SoLuongTon = 200,
                            TenSP = "Mi hao hao Chua cay",
                            TrangThaiSanPham = 0
                        },
                        new
                        {
                            MaSP = "SP004",
                            DanhMuc = "Gia vi",
                            DonGia = 55000m,
                            SoLuongTon = 30,
                            TenSP = "Dau an Simply 1L",
                            TrangThaiSanPham = 0
                        },
                        new
                        {
                            MaSP = "SP005",
                            DanhMuc = "Gia vi",
                            DonGia = 16000m,
                            SoLuongTon = 40,
                            TenSP = "Nuoc tuong Chinsu 250ml",
                            TrangThaiSanPham = 0
                        },
                        new
                        {
                            MaSP = "SP006",
                            DanhMuc = "Do uong",
                            DonGia = 10000m,
                            SoLuongTon = 120,
                            TenSP = "Coca Cola lon 320ml",
                            TrangThaiSanPham = 0
                        },
                        new
                        {
                            MaSP = "SP007",
                            DanhMuc = "Thuc pham kho",
                            DonGia = 190000m,
                            SoLuongTon = 15,
                            TenSP = "Gao Thom ST25 5kg",
                            TrangThaiSanPham = 0
                        },
                        new
                        {
                            MaSP = "SP008",
                            DanhMuc = "Hoa my pham",
                            DonGia = 175000m,
                            SoLuongTon = 10,
                            TenSP = "Nuoc giat Ariel 3.2kg",
                            TrangThaiSanPham = 0
                        },
                        new
                        {
                            MaSP = "SP009",
                            DanhMuc = "Hoa my pham",
                            DonGia = 32000m,
                            SoLuongTon = 0,
                            TenSP = "Khan uot Mamamy 80 to",
                            TrangThaiSanPham = 3
                        },
                        new
                        {
                            MaSP = "SP010",
                            DanhMuc = "Banh keo",
                            DonGia = 6000m,
                            SoLuongTon = 50,
                            TenSP = "Banh snack Oishi Bi do",
                            TrangThaiSanPham = 5
                        });
                });

            modelBuilder.Entity("QuanLyCuaHangTapHoa.Domain.TaiKhoan", b =>
                {
                    b.Property<string>("MaNguoiDung")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TrangThaiTaiKhoan")
                        .HasColumnType("int");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique();

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoans", (string)null);

                    b.HasData(
                        new
                        {
                            MaNguoiDung = "ND001",
                            MaTaiKhoan = "TK001",
                            MatKhau = "$2a$11$QWA6VYYwVuMeQt5URQjppuSYATFgmwKcp1xQ/LYfOXgFkqnB7dEVC",
                            TenDangNhap = "admin",
                            TrangThaiTaiKhoan = 0
                        },
                        new
                        {
                            MaNguoiDung = "ND002",
                            MaTaiKhoan = "TK002",
                            MatKhau = "$2a$11$6i8EYx0V/yxT6gkqIfdaFON4Q9GtLpGWQzTKbtjeR984fkStm0hiu",
                            TenDangNhap = "nhanvien",
                            TrangThaiTaiKhoan = 0
                        },
                        new
                        {
                            MaNguoiDung = "ND003",
                            MaTaiKhoan = "TK003",
                            MatKhau = "$2a$11$LcU9So22QpvpfW9jhdI0teIjIxFvsbuyO0D7lHGKFm9G2dezKk0Nm",
                            TenDangNhap = "khachhang",
                            TrangThaiTaiKhoan = 0
                        });
                });

            modelBuilder.Entity("QuanLyCuaHangTapHoa.Domain.KhachHang", b =>
                {
                    b.HasBaseType("QuanLyCuaHangTapHoa.Domain.NguoiDung");

                    b.Property<string>("MaKhachHang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.HasIndex("MaKhachHang")
                        .IsUnique()
                        .HasFilter("[MaKhachHang] IS NOT NULL");

                    b.ToTable("KhachHangs", (string)null);

                    b.HasData(
                        new
                        {
                            MaNguoiDung = "ND003",
                            DiaChi = "789 Lane, Da Nang",
                            Email = "customer@gmail.com",
                            HoTen = "Le Van Khach Hang",
                            SoDienThoai = "0900000003",
                            MaKhachHang = "KH001",
                            NgayDangKy = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("QuanLyCuaHangTapHoa.Domain.NhanVien", b =>
                {
                    b.HasBaseType("QuanLyCuaHangTapHoa.Domain.NguoiDung");

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasIndex("MaNhanVien")
                        .IsUnique()
                        .HasFilter("[MaNhanVien] IS NOT NULL");

                    b.ToTable("NhanViens", (string)null);

                    b.HasData(
                        new
                        {
                            MaNguoiDung = "ND002",
                            DiaChi = "456 Side St, Ha Noi",
                            Email = "staff@grocery.com",
                            HoTen = "Tran Thi Nhan Vien",
                            SoDienThoai = "0900000002",
                            ChucVu = "Thu Ngan",
                            MaNhanVien = "NV001"
                        });
                });

            modelBuilder.Entity("QuanLyCuaHangTapHoa.Domain.Admin", b =>
                {
                    b.HasBaseType("QuanLyCuaHangTapHoa.Domain.NhanVien");

                    b.ToTable("Admins", (string)null);

                    b.HasData(
                        new
                        {
                            MaNguoiDung = "ND001",
                            DiaChi = "123 Main St, Ha Noi",
                            Email = "admin@grocery.com",
                            HoTen = "Nguyen Van Admin",
                            SoDienThoai = "0900000001",
                            ChucVu = "Quan Tri Vien",
                            MaNhanVien = "NV000"
                        });
                });

            modelBuilder.Entity("QuanLyCuaHangTapHoa.Domain.ChiTietDonHang", b =>
                {
                    b.HasOne("QuanLyCuaHangTapHoa.Domain.DonDatHang", "DonDatHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyCuaHangTapHoa.Domain.SanPham", "SanPham")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonDatHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("QuanLyCuaHangTapHoa.Domain.DonDatHang", b =>
                {
                    b.HasOne("QuanLyCuaHangTapHoa.Domain.KhachHang", "KhachHang")
                        .WithMany("DonDatHangs")
                        .HasForeignKey("MaNguoiDungKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("QuanLyCuaHangTapHoa.Domain.HoaDon", b =>
                {
                    b.HasOne("QuanLyCuaHangTapHoa.Domain.DonDatHang", "DonDatHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyCuaHangTapHoa.Domain.NhanVien", "NhanVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNguoiDungNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonDatHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyCuaHangTapHoa.Domain.TaiKhoan", b =>
                {
                    b.HasOne("QuanLyCuaHangTapHoa.Domain.NguoiDung", "NguoiDung")
                        .WithOne("TaiKhoan")
                        .HasForeignKey("QuanLyCuaHangTapHoa.Domain.TaiKhoan", "MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QuanLyCuaHangTapHoa.Domain.KhachHang", b =>
                {
                    b.HasOne("QuanLyCuaHangTapHoa.Domain.NguoiDung", null)
                        .WithOne()
                        .HasForeignKey("QuanLyCuaHangTapHoa.Domain.KhachHang", "MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyCuaHangTapHoa.Domain.NhanVien", b =>
                {
                    b.HasOne("QuanLyCuaHangTapHoa.Domain.NguoiDung", null)
                        .WithOne()
                        .HasForeignKey("QuanLyCuaHangTapHoa.Domain.NhanVien", "MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyCuaHangTapHoa.Domain.Admin", b =>
                {
                    b.HasOne("QuanLyCuaHangTapHoa.Domain.NhanVien", null)
                        .WithOne()
                        .HasForeignKey("QuanLyCuaHangTapHoa.Domain.Admin", "MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyCuaHangTapHoa.Domain.DonDatHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("QuanLyCuaHangTapHoa.Domain.NguoiDung", b =>
                {
                    b.Navigation("TaiKhoan")
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyCuaHangTapHoa.Domain.SanPham", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("QuanLyCuaHangTapHoa.Domain.KhachHang", b =>
                {
                    b.Navigation("DonDatHangs");
                });

            modelBuilder.Entity("QuanLyCuaHangTapHoa.Domain.NhanVien", b =>
                {
                    b.Navigation("HoaDons");
                });
#pragma warning restore 612, 618
        }
    }
}
